# These are supported funding model platforms
# Funding configuration for 港中深智慧校园开发团队 (CUHKSZ Smart Campus Development Team)
# 
# Note: This project is based on the work of blazickjp/arxiv-mcp-server
# Original project funding: github: blazickjp

# Uncomment and add your GitHub Sponsors username if you want to enable funding
github: LKCY23
